# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83ff71365428d53b990865f0d2be3c6a7ac5ee045cc42642ed3671c3fbed9478f1b4dd9ae6ade54de2ecb8cee2393b819632705593985365e38acfd59528353e

test:
  secret_key_base: cdc2857f0c17520f24b081a3965fa03fa3165d24e4faa4fba347c24021abbc35f7bce3572bec72cd0b5ab3a2795f6d20c6646c03eb20fb4302d107f1c798e517

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
